import type { WorkoutTemplate } from "./types";

export const fullBodyTemplate: WorkoutTemplate = {
  key: "full-body",
  name: "Full Body",
  description:
    "Efficient 3-day program hitting all major muscle groups each session",
  splitType: "full_body",
  daysPerWeek: 3,
  days: [
    {
      name: "Full Body A",
      targetMuscles: [
        "chest",
        "back",
        "shoulders",
        "quads",
        "hamstrings",
        "glutes",
        "biceps",
        "triceps",
      ],
      exercises: [
        {
          exerciseId: "bb-squat",
          exerciseName: "Barbell Squat",
          targetSets: 4,
          targetReps: "6-8",
          restSeconds: 120,
        },
        {
          exerciseId: "bb-bench-press",
          exerciseName: "Barbell Bench Press",
          targetSets: 4,
          targetReps: "6-8",
          restSeconds: 120,
        },
        {
          exerciseId: "bb-bent-over-row",
          exerciseName: "Barbell Bent-Over Row",
          targetSets: 3,
          targetReps: "8-10",
          restSeconds: 90,
        },
        {
          exerciseId: "db-shoulder-press",
          exerciseName: "Dumbbell Shoulder Press",
          targetSets: 3,
          targetReps: "8-10",
          restSeconds: 90,
        },
        {
          exerciseId: "bb-romanian-deadlift",
          exerciseName: "Barbell Romanian Deadlift",
          targetSets: 3,
          targetReps: "8-10",
          restSeconds: 90,
        },
        {
          exerciseId: "db-bicep-curl",
          exerciseName: "Dumbbell Bicep Curl",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 60,
        },
        {
          exerciseId: "cable-tricep-pushdown",
          exerciseName: "Cable Tricep Pushdown",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 60,
        },
      ],
    },
    {
      name: "Full Body B",
      targetMuscles: [
        "chest",
        "back",
        "shoulders",
        "quads",
        "hamstrings",
        "glutes",
        "calves",
      ],
      exercises: [
        {
          exerciseId: "bb-deadlift",
          exerciseName: "Barbell Deadlift",
          targetSets: 4,
          targetReps: "5-6",
          restSeconds: 120,
          notes: "Focus on hip hinge and bracing",
        },
        {
          exerciseId: "db-incline-bench-press",
          exerciseName: "Dumbbell Incline Bench Press",
          targetSets: 3,
          targetReps: "8-10",
          restSeconds: 90,
        },
        {
          exerciseId: "lat-pulldown",
          exerciseName: "Lat Pulldown",
          targetSets: 3,
          targetReps: "8-10",
          restSeconds: 90,
        },
        {
          exerciseId: "leg-press",
          exerciseName: "Leg Press",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 90,
        },
        {
          exerciseId: "db-lateral-raise",
          exerciseName: "Dumbbell Lateral Raise",
          targetSets: 3,
          targetReps: "12-15",
          restSeconds: 60,
        },
        {
          exerciseId: "cable-face-pull",
          exerciseName: "Cable Face Pull",
          targetSets: 3,
          targetReps: "12-15",
          restSeconds: 60,
        },
        {
          exerciseId: "standing-calf-raise",
          exerciseName: "Standing Calf Raise",
          targetSets: 4,
          targetReps: "12-15",
          restSeconds: 60,
        },
      ],
    },
    {
      name: "Full Body C",
      targetMuscles: [
        "chest",
        "back",
        "shoulders",
        "quads",
        "hamstrings",
        "glutes",
        "biceps",
        "triceps",
      ],
      exercises: [
        {
          exerciseId: "bb-front-squat",
          exerciseName: "Barbell Front Squat",
          targetSets: 4,
          targetReps: "6-8",
          restSeconds: 120,
        },
        {
          exerciseId: "bb-overhead-press",
          exerciseName: "Barbell Overhead Press",
          targetSets: 4,
          targetReps: "6-8",
          restSeconds: 120,
        },
        {
          exerciseId: "pull-up",
          exerciseName: "Pull-Up",
          targetSets: 3,
          targetReps: "6-10",
          restSeconds: 120,
          notes: "Add weight if bodyweight is too easy",
        },
        {
          exerciseId: "db-bench-press",
          exerciseName: "Dumbbell Bench Press",
          targetSets: 3,
          targetReps: "8-10",
          restSeconds: 90,
        },
        {
          exerciseId: "hip-thrust",
          exerciseName: "Hip Thrust",
          targetSets: 3,
          targetReps: "8-10",
          restSeconds: 90,
        },
        {
          exerciseId: "bb-curl",
          exerciseName: "Barbell Curl",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 60,
        },
        {
          exerciseId: "dip",
          exerciseName: "Dip",
          targetSets: 3,
          targetReps: "8-12",
          restSeconds: 90,
        },
      ],
    },
  ],
};
