import type { WorkoutTemplate } from "./types";

export const pplTemplate: WorkoutTemplate = {
  key: "ppl",
  name: "Push / Pull / Legs",
  description:
    "Classic 6-day split targeting each muscle group twice per week",
  splitType: "ppl",
  daysPerWeek: 6,
  days: [
    {
      name: "Push",
      targetMuscles: ["chest", "shoulders", "triceps"],
      exercises: [
        {
          exerciseId: "bb-bench-press",
          exerciseName: "Barbell Bench Press",
          targetSets: 4,
          targetReps: "6-8",
          restSeconds: 120,
        },
        {
          exerciseId: "db-shoulder-press",
          exerciseName: "Dumbbell Shoulder Press",
          targetSets: 3,
          targetReps: "8-10",
          restSeconds: 90,
        },
        {
          exerciseId: "db-incline-bench-press",
          exerciseName: "Dumbbell Incline Bench Press",
          targetSets: 3,
          targetReps: "8-12",
          restSeconds: 90,
        },
        {
          exerciseId: "cable-lateral-raise",
          exerciseName: "Cable Lateral Raise",
          targetSets: 3,
          targetReps: "12-15",
          restSeconds: 60,
        },
        {
          exerciseId: "cable-tricep-pushdown",
          exerciseName: "Cable Tricep Pushdown",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 60,
        },
        {
          exerciseId: "db-chest-fly",
          exerciseName: "Dumbbell Chest Fly",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 60,
        },
        {
          exerciseId: "overhead-tricep-extension",
          exerciseName: "Overhead Tricep Extension",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 60,
        },
      ],
    },
    {
      name: "Pull",
      targetMuscles: ["back", "biceps"],
      exercises: [
        {
          exerciseId: "bb-deadlift",
          exerciseName: "Barbell Deadlift",
          targetSets: 4,
          targetReps: "5-6",
          restSeconds: 120,
          notes: "Focus on hip hinge and bracing",
        },
        {
          exerciseId: "lat-pulldown",
          exerciseName: "Lat Pulldown",
          targetSets: 3,
          targetReps: "8-10",
          restSeconds: 90,
        },
        {
          exerciseId: "bb-bent-over-row",
          exerciseName: "Barbell Bent-Over Row",
          targetSets: 3,
          targetReps: "8-10",
          restSeconds: 90,
        },
        {
          exerciseId: "cable-face-pull",
          exerciseName: "Cable Face Pull",
          targetSets: 3,
          targetReps: "12-15",
          restSeconds: 60,
        },
        {
          exerciseId: "db-bicep-curl",
          exerciseName: "Dumbbell Bicep Curl",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 60,
        },
        {
          exerciseId: "seated-cable-row",
          exerciseName: "Seated Cable Row",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 90,
        },
      ],
    },
    {
      name: "Legs",
      targetMuscles: ["quads", "hamstrings", "glutes", "calves"],
      exercises: [
        {
          exerciseId: "bb-squat",
          exerciseName: "Barbell Squat",
          targetSets: 4,
          targetReps: "6-8",
          restSeconds: 120,
        },
        {
          exerciseId: "bb-romanian-deadlift",
          exerciseName: "Barbell Romanian Deadlift",
          targetSets: 3,
          targetReps: "8-10",
          restSeconds: 90,
        },
        {
          exerciseId: "leg-press",
          exerciseName: "Leg Press",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 90,
        },
        {
          exerciseId: "leg-curl",
          exerciseName: "Leg Curl",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 60,
        },
        {
          exerciseId: "leg-extension",
          exerciseName: "Leg Extension",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 60,
        },
        {
          exerciseId: "standing-calf-raise",
          exerciseName: "Standing Calf Raise",
          targetSets: 4,
          targetReps: "12-15",
          restSeconds: 60,
        },
      ],
    },
    {
      name: "Push 2",
      targetMuscles: ["chest", "shoulders", "triceps"],
      exercises: [
        {
          exerciseId: "db-bench-press",
          exerciseName: "Dumbbell Bench Press",
          targetSets: 4,
          targetReps: "8-10",
          restSeconds: 90,
        },
        {
          exerciseId: "bb-overhead-press",
          exerciseName: "Barbell Overhead Press",
          targetSets: 3,
          targetReps: "6-8",
          restSeconds: 120,
        },
        {
          exerciseId: "cable-chest-fly",
          exerciseName: "Cable Chest Fly",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 60,
        },
        {
          exerciseId: "db-lateral-raise",
          exerciseName: "Dumbbell Lateral Raise",
          targetSets: 3,
          targetReps: "12-15",
          restSeconds: 60,
        },
        {
          exerciseId: "dip",
          exerciseName: "Dip",
          targetSets: 3,
          targetReps: "8-12",
          restSeconds: 90,
          notes: "Lean forward slightly for chest emphasis",
        },
        {
          exerciseId: "db-overhead-tricep-extension",
          exerciseName: "Dumbbell Overhead Tricep Extension",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 60,
        },
      ],
    },
    {
      name: "Pull 2",
      targetMuscles: ["back", "biceps"],
      exercises: [
        {
          exerciseId: "pull-up",
          exerciseName: "Pull-Up",
          targetSets: 4,
          targetReps: "6-10",
          restSeconds: 120,
          notes: "Add weight if bodyweight is too easy",
        },
        {
          exerciseId: "db-row",
          exerciseName: "Dumbbell Row",
          targetSets: 3,
          targetReps: "8-10",
          restSeconds: 90,
        },
        {
          exerciseId: "cable-pullover",
          exerciseName: "Cable Pullover",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 60,
        },
        {
          exerciseId: "cable-face-pull",
          exerciseName: "Cable Face Pull",
          targetSets: 3,
          targetReps: "12-15",
          restSeconds: 60,
        },
        {
          exerciseId: "bb-curl",
          exerciseName: "Barbell Curl",
          targetSets: 3,
          targetReps: "8-10",
          restSeconds: 60,
        },
        {
          exerciseId: "incline-db-curl",
          exerciseName: "Incline Dumbbell Curl",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 60,
        },
      ],
    },
    {
      name: "Legs 2",
      targetMuscles: ["quads", "hamstrings", "glutes", "calves"],
      exercises: [
        {
          exerciseId: "bb-front-squat",
          exerciseName: "Barbell Front Squat",
          targetSets: 4,
          targetReps: "6-8",
          restSeconds: 120,
        },
        {
          exerciseId: "db-walking-lunge",
          exerciseName: "Dumbbell Walking Lunge",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 90,
          notes: "10-12 reps per leg",
        },
        {
          exerciseId: "leg-curl",
          exerciseName: "Leg Curl",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 60,
        },
        {
          exerciseId: "hip-thrust",
          exerciseName: "Hip Thrust",
          targetSets: 3,
          targetReps: "8-10",
          restSeconds: 90,
        },
        {
          exerciseId: "leg-extension",
          exerciseName: "Leg Extension",
          targetSets: 3,
          targetReps: "12-15",
          restSeconds: 60,
        },
        {
          exerciseId: "seated-calf-raise",
          exerciseName: "Seated Calf Raise",
          targetSets: 4,
          targetReps: "12-15",
          restSeconds: 60,
        },
      ],
    },
  ],
};
