import type { WorkoutTemplate } from "./types";

export const upperLowerTemplate: WorkoutTemplate = {
  key: "upper-lower",
  name: "Upper / Lower",
  description:
    "Balanced 4-day split with two upper and two lower body days",
  splitType: "upper_lower",
  daysPerWeek: 4,
  days: [
    {
      name: "Upper A",
      targetMuscles: ["chest", "back", "shoulders", "biceps", "triceps"],
      exercises: [
        {
          exerciseId: "bb-bench-press",
          exerciseName: "Barbell Bench Press",
          targetSets: 4,
          targetReps: "6-8",
          restSeconds: 120,
        },
        {
          exerciseId: "bb-bent-over-row",
          exerciseName: "Barbell Bent-Over Row",
          targetSets: 4,
          targetReps: "6-8",
          restSeconds: 120,
        },
        {
          exerciseId: "db-shoulder-press",
          exerciseName: "Dumbbell Shoulder Press",
          targetSets: 3,
          targetReps: "8-10",
          restSeconds: 90,
        },
        {
          exerciseId: "lat-pulldown",
          exerciseName: "Lat Pulldown",
          targetSets: 3,
          targetReps: "8-10",
          restSeconds: 90,
        },
        {
          exerciseId: "db-bicep-curl",
          exerciseName: "Dumbbell Bicep Curl",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 60,
        },
        {
          exerciseId: "cable-tricep-pushdown",
          exerciseName: "Cable Tricep Pushdown",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 60,
        },
        {
          exerciseId: "db-lateral-raise",
          exerciseName: "Dumbbell Lateral Raise",
          targetSets: 3,
          targetReps: "12-15",
          restSeconds: 60,
        },
      ],
    },
    {
      name: "Lower A",
      targetMuscles: ["quads", "hamstrings", "glutes", "calves"],
      exercises: [
        {
          exerciseId: "bb-squat",
          exerciseName: "Barbell Squat",
          targetSets: 4,
          targetReps: "6-8",
          restSeconds: 120,
        },
        {
          exerciseId: "bb-romanian-deadlift",
          exerciseName: "Barbell Romanian Deadlift",
          targetSets: 3,
          targetReps: "8-10",
          restSeconds: 90,
        },
        {
          exerciseId: "leg-press",
          exerciseName: "Leg Press",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 90,
        },
        {
          exerciseId: "leg-curl",
          exerciseName: "Leg Curl",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 60,
        },
        {
          exerciseId: "db-walking-lunge",
          exerciseName: "Dumbbell Walking Lunge",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 90,
          notes: "10-12 reps per leg",
        },
        {
          exerciseId: "standing-calf-raise",
          exerciseName: "Standing Calf Raise",
          targetSets: 4,
          targetReps: "12-15",
          restSeconds: 60,
        },
      ],
    },
    {
      name: "Upper B",
      targetMuscles: ["chest", "back", "shoulders", "biceps", "triceps"],
      exercises: [
        {
          exerciseId: "db-incline-bench-press",
          exerciseName: "Dumbbell Incline Bench Press",
          targetSets: 4,
          targetReps: "8-10",
          restSeconds: 90,
        },
        {
          exerciseId: "pull-up",
          exerciseName: "Pull-Up",
          targetSets: 4,
          targetReps: "6-10",
          restSeconds: 120,
          notes: "Add weight if bodyweight is too easy",
        },
        {
          exerciseId: "cable-chest-fly",
          exerciseName: "Cable Chest Fly",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 60,
        },
        {
          exerciseId: "seated-cable-row",
          exerciseName: "Seated Cable Row",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 90,
        },
        {
          exerciseId: "cable-face-pull",
          exerciseName: "Cable Face Pull",
          targetSets: 3,
          targetReps: "12-15",
          restSeconds: 60,
        },
        {
          exerciseId: "bb-curl",
          exerciseName: "Barbell Curl",
          targetSets: 3,
          targetReps: "8-10",
          restSeconds: 60,
        },
        {
          exerciseId: "dip",
          exerciseName: "Dip",
          targetSets: 3,
          targetReps: "8-12",
          restSeconds: 90,
        },
      ],
    },
    {
      name: "Lower B",
      targetMuscles: ["quads", "hamstrings", "glutes", "calves"],
      exercises: [
        {
          exerciseId: "bb-deadlift",
          exerciseName: "Barbell Deadlift",
          targetSets: 4,
          targetReps: "5-6",
          restSeconds: 120,
          notes: "Focus on hip hinge and bracing",
        },
        {
          exerciseId: "bb-front-squat",
          exerciseName: "Barbell Front Squat",
          targetSets: 3,
          targetReps: "8-10",
          restSeconds: 120,
        },
        {
          exerciseId: "hip-thrust",
          exerciseName: "Hip Thrust",
          targetSets: 3,
          targetReps: "8-10",
          restSeconds: 90,
        },
        {
          exerciseId: "leg-extension",
          exerciseName: "Leg Extension",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 60,
        },
        {
          exerciseId: "leg-curl",
          exerciseName: "Leg Curl",
          targetSets: 3,
          targetReps: "10-12",
          restSeconds: 60,
        },
        {
          exerciseId: "seated-calf-raise",
          exerciseName: "Seated Calf Raise",
          targetSets: 4,
          targetReps: "12-15",
          restSeconds: 60,
        },
      ],
    },
  ],
};
